config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pages, only: [] do
    collection do
      get 'leaderboard'
      get 'status'
      get 'history'
    end
  end

  resources :games do
    resources :game_users, only: [:create, :destroy]
    resources :rounds, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "games#index"
end

app/models/game.rb
require_relative 'player'
require_relative 'go_fish'

class Game < ApplicationRecord
  class GoFishError < StandardError; end

  has_many :game_users, dependent: :destroy
  has_many :users, through: :game_users

  validates :name, presence: true
  validates :required_player_count, presence: true, numericality: { only_integer: true, greater_than: 1 }

  serialize :go_fish, coder: GoFish

  scope :joinable, -> { order(created_at: :desc).where(started_at: nil) }
  scope :in_progress, -> { order(created_at: :desc).where.not(started_at: nil).where(finished_at: nil) }
  scope :finished, -> { order(created_at: :desc).where.not(finished_at: nil) }

  paginates_per 10

  after_update_commit lambda {
    users.each do |user|
      broadcast_refresh_to "games:#{id}:users:#{user.id}"
    end
    # TODO: Only when user is on that page
    broadcast_refresh_to 'status' if started? && !finished?
    broadcast_refresh_to 'history' if finished?
  }

  def enough_players?
    users.count == required_player_count
  end

  def started?
    !go_fish.nil?
  end

  def finished?
    go_fish&.winners&.any?
  end

  def can_take_turn?(current_user)
    go_fish.current_player.user_id == current_user.id && go_fish.winners.empty?
  end

  def start!
    update(users:)
    return false unless required_player_count == users.count

    players = users.map { |user| Player.new(user_id: user.id) }
    go_fish = GoFish.new(players:)
    go_fish.deal!
    # update started_at: DateTime.current
    update(go_fish:, started_at: DateTime.current)
  end

  def play_round!(opponent_user_id, rank)
    opponent = go_fish.players.find { |player| player.user_id == opponent_user_id }
    go_fish.play_round!(opponent, rank)
    complete_round
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[name]
  end

  def generate_score(player)
    player.books.sum(&:value)
  end

  private

  def complete_round
    if finished?
      winner_ids = go_fish.winners.map(&:user_id)

      game_users.each do |game_user|
        update_game_user(game_user, winner_ids)
      end

      update(finished_at: DateTime.current)
    else
      save!
    end
  end

  def update_game_user(game_user, winner_ids)
    is_winner = winner_ids.include?(game_user.user_id)
    player = go_fish.players.find { |p| p.user_id == game_user.user_id }
    score = is_winner ? generate_score(player) : 0
    game_user.update(winner: is_winner, score:)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game, only: %i[show edit update destroy]

  def index
    @my_games = current_user.games

    @q = Game.joinable.ransack(params[:q])
    @games = @q.result.page(params[:page])
  end

  def show
  end

  def new
    @game = Game.build
    @path = games_path
    render layout: 'modal'
  end

  def edit
    @path = @game
    render layout: 'modal'
  end

  def create
    @game = Game.build(game_params)

    if @game.save
      @game.users << current_user
      redirect_to games_path, notice: 'Game was successfully created.'
    else
      render :new, status: :unprocessable_entity, layout: 'modal'
    end
  end

  def update
    if @game.update(game_params)
      redirect_to games_path, notice: 'Game was successfully updated.'
    else
      render :edit, status: :unprocessable_entity, layout: 'modal'
    end
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_path, notice: 'Game was successfully destroyed.' }
      format.turbo_stream { flash.now[:notice] = 'Game was successfully destroyed.' }
    end
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:name, :required_player_count, :_method, :authenticity_token, :commit)
  end
end

app/views/games/_form.html.slim
= simple_form_for @game do |f|
  = f.input :name
  = f.input :required_player_count unless editing

  = content_for :modal_actions
    = f.submit class: "btn-primary", form: f.id

app/views/games/_game_info.html.slim
= turbo_frame_tag game
  .game-row
    span #{game.name}
    .game-actions
      - if !game.started?
        span.game-actions__player-count #{game.users.count}/#{game.required_player_count} Players
      - else
        span.game-actions__player-count Game is Full

      - if current_user.games.include?(game)
        = link_to game_path(game), data: { turbo_frame: "_top" }, class: 'btn game-actions__button' do
          | Play Now
          span.material-symbols-outlined arrow_right
      - elsif !game.enough_players?
        = button_to 'Join Game', game_game_users_path(game), method: :post, class: 'btn game-actions__button', data: { turbo_frame: "_top" }
      - else
        button.btn.game-actions__button.disabled In Progress

app/views/games/create.turbo_stream.slim
= turbo_stream.prepend "your_games", partial: "game_info", locals: { game: @game }
= turbo_stream.prepend "all_games", partial: "game_info", locals: { game: @game }
= turbo_stream.update Game.new, ""
= render_turbo_stream_flash_messages

app/views/games/destroy.turbo_stream.slim
= turbo_stream.remove_all @game
  = render partial: 'game_info', locals: { game: @game }
= render_turbo_stream_flash_messages

app/views/games/edit.html.slim
= content_for :modal_title
  h1 Edit Game

= render "form", editing: true

app/views/games/index.html.slim
main.container
  section.games-section
    .games-section__game-header
      span.gf-emphasis Your Games
      = modal_link_to new_game_path, class: 'btn-primary' do
        span.material-symbols-outlined add
        | New Game
    = turbo_frame_tag "your_games", class: "games-section__game-rows"
      - if @my_games.any?
        - @my_games.each do |game|
          - unless game.go_fish && game.go_fish.winners.any?
            = render "game_info", game: game
      - else
        p You have no active games.

  section.games-section
    .games-section__game-header
      span.gf-emphasis All Games
    = render 'shared/search_form', target: @games, url: games_path, search_field: :name_cont
    = turbo_frame_tag "all_games", class: "games-section__game-rows"
      - @games.each do |game|
        - unless game.go_fish && game.go_fish.winners.any?
          = render "game_info", game: game

app/views/games/new.html.slim
= content_for :modal_title
  h1 New Game

= render "form", editing: false

app/views/games/show.html.slim
= turbo_stream_from "games:#{@game.id}:users:#{current_user.id}"

- if @game.started?
  main.game-view
    section.gf-panel.gf-panel--large-header-row.board-view
      .gf-panel__panel-header.gf-panel__panel-header--large
        = link_to games_path do
          span.material-symbols-outlined.icon--x-large.icon--weight-bold arrow_back
        span.gf-emphasis = @game.name
      .gf-panel__panel-body.gf-panel__panel-body--players
        span.gf-emphasis Players:
        .accordion-group
          - @game.go_fish.players.each do |player|
            details.accordion
              summary
                span.material-symbols-outlined.accordion__marker arrow_right
                .flex.justify-between
                  - if player.user_id == current_user.id
                    span.gf-emphasis = player.name
                  - else
                    span = player.name

                  .flex.gap-xl
                    span
                      |> Cards:
                      span.gf-emphasis = player.hand.size
                    span
                      |> Books:
                      span.gf-emphasis = player.books.size

              .card-tray.card-tray--border-top
                .card-row.card-row--accordion
                  - if player.user_id == current_user.id
                    - player.hand.each do |card|
                      = image_tag "#{card.rank.downcase}-#{card.suit.downcase}.svg", alt: "#{card.rank} of #{card.suit}"
                  - else
                    - player.hand.each do |card|
                      = image_tag "back-card.svg", alt: "#{card.rank} of #{card.suit}"
                .card-row.card-row--accordion-books
                  - player.books.each do |book|
                    - card = book.cards.first
                    = image_tag "#{card.rank.downcase}-#{card.suit.downcase}.svg", alt: "#{card.rank} of #{card.suit}"


    section.gf-panel.gf-panel--large-header-row.feed-view
      .gf-panel__panel-header.justify-between
        span.gf-emphasis Game Feed
        .badge-primary.badge--with-border #{@game.go_fish.current_player.name}'s Turn
      .gf-panel__panel-body.gf-panel__panel-body--feed
        .notification-feed data-controller="notification-feed"
          - if @game.go_fish.winners.any?
            - if current_user.id == @game.go_fish.round_results.last.current_player.user_id
              - context = :player
            - else
              - context = :others
            .notification
              span = @game.go_fish.round_results.last.messages_for(context)['game_over']

          - @game.go_fish.round_results&.each do |round_result|
            - if current_user.id == round_result.current_player.user_id
              - context = :player
            - elsif current_user.id == round_result.opponent.user_id
              - context = :opponent
            - else
              - context = :others

            - messages = round_result.messages_for(context)

            .notification-feed__round-result id="#{round_result.id}" data-notification-feed-target="item"
              .notification.notification--action
                span = messages['action']
              .notification-feed__reply
                span.material-symbols-outlined.icon--x-large.icon--weight-semi-bold subdirectory_arrow_right
                .notification.notification--response
                  span.gf-emphasis = messages['response']
              .notification-feed__reply
                span.material-symbols-outlined.icon--x-large.icon--weight-semi-bold subdirectory_arrow_right
                .notification.notification--feedback
                  span.gf-emphasis = messages['feedback']
              - if messages['book']
                .notification-feed__reply
                  span.material-symbols-outlined.icon--x-large.icon--weight-semi-bold subdirectory_arrow_right
                  .notification.notification--feedback
                    span.gf-emphasis = messages['book']

        = form_for @game, url: game_rounds_path(@game), method: :post, html: { class: "action-choices" } do |f|
          .action-choices__input-collection
            .form-group.flex-grow-1
              = label_tag :opponent_id, "Player", class: "form-label"
              = select_tag :opponent_id, options_for_select(@game.go_fish.players.reject { |player| player.user_id == current_user.id }.map { |player| [player.name, player.user_id] }), class: "form-control form-control--small"

            .form-group.flex-grow-1
              span.form-label Card Rank
              .rank-selector(data-controller="rank-selector")
                = hidden_field_tag :rank, '', data: { "rank-selector-target": 'input' }
                - @game.go_fish.players.find { |player| player.user_id == current_user.id }.hand.map { |card| card.rank }.uniq.each do |rank|
                  = button_tag rank, class: "btn btn--small", data: { action: 'click->rank-selector#select', "rank-selector-target": 'button', rank: rank }

          - if @game.go_fish.winners.any?
            = link_to 'Leave Game', games_path, data: { confirm: 'Are you ready leave this game?' }, class: "btn-primary"
          - elsif @game.can_take_turn?(current_user)
            = f.submit "Ask for Cards", class: "btn-primary"
          - else
            = f.submit "Ask for Cards", class: "btn-primary", disabled: true

    - player = @game.go_fish.players.find { |player| player.user_id == current_user.id }
    section.gf-panel.hand-view
      .gf-panel__panel-header
        span.gf-emphasis Your Hand
      .card-tray
        .card-row
          - player = @game.go_fish.players.find { |player| player.user_id == current_user.id }
          - player.hand.each do |card|
                = image_tag "#{card.rank.downcase}-#{card.suit.downcase}.svg", alt: "#{card.rank} of #{card.suit}"

    section.gf-panel.book-view
      .gf-panel__panel-header
        span.gf-emphasis Your Books
      .card-tray
        .card-row.card-row--your-books
          - player.books.each do |book|
            - card = book.cards.first
            = image_tag "#{card.rank.downcase}-#{card.suit.downcase}.svg", alt: "#{card.rank} of #{card.suit}"

- else
  main.game-view
    section.gf-panel.gf-panel--large-header-row.board-view
      .gf-panel__panel-header.gf-panel__panel-header--large
        = link_to games_path do
          span.material-symbols-outlined.icon--x-large.icon--weight-bold arrow_back
        span.gf-emphasis = @game.name
      .gf-panel__panel-body.gf-panel__panel-body--players
        span.gf-emphasis Waiting for Players...
        span #{@game.users.count}/#{@game.required_player_count} Players
        ul
          - @game.users.each do |user|
            li = user.name

    section.gf-panel.gf-panel--large-header-row.feed-view
      .gf-panel__panel-header.justify-between
        span.gf-emphasis Game Feed
        .badge-primary.badge--with-border Waiting
      .gf-panel__panel-body.gf-panel__panel-body--feed

    section.gf-panel.hand-view
      .gf-panel__panel-header
        span.gf-emphasis Your Hand
      .card-tray

    section.gf-panel.book-view
      .gf-panel__panel-header
        span.gf-emphasis Your Books
      .card-tray

app/views/games/update.turbo_stream.slim
= turbo_stream.update_all @game
  = render partial: 'game_info', locals: { game: @game }
= render_turbo_stream_flash_messages