config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :pages, only: [] do
    collection do
      get 'leaderboard'
      get 'status'
      get 'history'
    end
  end

  resources :games do
    resources :game_users, only: [:create, :destroy]
    resources :rounds, only: [:create]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "games#index"
end

app/views/layouts/_flash.html.slim
- flash.each do |flash_type, message|
  .alert--flash class="alert-#{flash_type}" data-controller="removals" data-action="animationend->removals#remove"
    = message

app/views/layouts/_sidebar.html.slim
nav.sidebar.sidebar--drawer
  .sidebar__brand
    = image_tag "Go-Fish-Logo.png", alt: "Go Fish Logo"
  .sidebar__content.sidebar__content--start
    = link_to games_path, class: 'btn btn--no-border'
      span.material-symbols-outlined.icon--outlined.icon--medium.icon--weight-normal.icon--normal-emphasis sports_esports
      | Games
    = link_to leaderboard_pages_path, class: 'btn btn--no-border'
      span.material-symbols-outlined.icon--outlined.icon--medium.icon--weight-normal.icon--normal-emphasis social_leaderboard
      | Leaderboard
    = link_to status_pages_path, class: 'btn btn--no-border'
      span.material-symbols-outlined.icon--outlined.icon--medium.icon--weight-normal.icon--normal-emphasis bar_chart
      | Game Status
    = link_to history_pages_path, class: 'btn btn--no-border'
      span.material-symbols-outlined.icon--outlined.icon--medium.icon--weight-normal.icon--normal-emphasis book_2
      | Game History


  .sidebar__content.sidebar__content--end
    .divider
    / button.btn.btn--no-border
    /   span.material-symbols-outlined.icon--outlined.icon--medium.icon--weight-normal.icon--normal-emphasis person
    /   | Profile

    = button_to destroy_user_session_path, method: :delete, class: 'btn btn--no-border'
      span.material-symbols-outlined.icon--outlined.icon--medium.icon--weight-normal.icon--normal-emphasis logout
      | Log Out

app/views/layouts/application.html.slim
doctype html
html lang="en" data-theme-mode="dark" data-theme="cyan"
  head
    title Go Fish Rails
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
    / meta name="view-transition" content="same-origin"
    meta name="turbo-refresh-method" content="morph"
    meta name="turbo-refresh-scroll" content="preserve"
    meta content="width=device-width, initial-scale=1" name="viewport"
  - is_game_show_page = controller_name == 'games' && action_name == 'show'
  - body_class = is_game_show_page ? '' : 'app-with-sidebar'
  - content_class = is_game_show_page ? '' : 'app__content'
  body class=body_class
    - unless is_game_show_page
      = render 'layouts/sidebar'
    .app-body
      #flash
        = render 'layouts/flash'
      = turbo_frame_tag 'modal'
      = turbo_frame_tag 'panel'
      = render 'confirm'
      div class=content_class
        = yield

app/views/layouts/modal.html.slim
doctype html
html
  head
    title Go Fish Rails
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
  body
    = turbo_frame_tag 'modal' do
      .modal-wrapper(
        class=class_names('modal-wrapper--active' => response.status == 422)
        data-controller="toggle"
        data-toggle-perform-on-connect-value=(response.message == 'OK')
        data-toggle-active-class="modal-wrapper--active"
        data-turbo-cache="false"
        data-action="keydown.esc@window->toggle#off"
      )
        .modal-wrapper__backdrop data-action="click->toggle#off"
        .modal data-testid="modal-content"
          .modal__header
            = yield :modal_title
            = button_tag( material_icon('close', size: 'x-large'), class: 'btn btn--no-border btn--icon btn--pill', data: { action: "toggle#off" })

          .modal__body
            = yield

          .modal__footer
            = button_tag( 'Cancel', class: 'btn', data: { action: "toggle#off" })
            = yield :modal_actions

app/views/layouts/panel.html.slim
doctype html
html
  head
    title Go Fish Rails
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
  body
    = turbo_frame_tag 'panel' do
      .panel.flex.items-center.justify-center(
        data-testid='panel'
        class=class_names('panel--active' => response.message == 'Unprocessable Entity')
        data-controller="toggle"
        data-toggle-perform-on-connect-value=(response.message == 'OK')
        data-toggle-active-class="panel--active"
        data-turbo-cache="false"
      )
        .panel__content
          .modal-nav
            .panel__close data-action="click->toggle#perform"
              = icon('close')
          .panel__body
            = yield